#!/usr/bin/env bash
# Script to configure domain zone to point to a load balancer
# Add more subdomains and display information about them

# Set domain and subdomains
domain="$1"
if [ "$#" -eq 2 ]; then
    sub="$2"
else
    sub=("www" "lb-01" "web-01" "web-02")
fi

# Iterate through subdomains
for subdomain in "${sub[@]}"; do
    # Display information about each subdomain
    echo -n "The subdomain $subdomain"
    dig_result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1)
    record_type=$(echo "$dig_result" | awk '{ print $4 }')
    target=$(echo "$dig_result" | awk '{ print $5 }')
    echo " is a $record_type record and points to $target"
done

