#!/usr/bin/env bash
# Bash script to install and start Nginx on a server

# Update package information and install Nginx
sudo apt-get -y update && sudo apt-get install -y nginx

# Change index.html to read "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Start Nginx service
sudo service nginx start
