#!/usr/bin/env bash
# Bash script to install Nginx with a custom 404 Error page

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create directory and files for custom 404 page
sudo mkdir /etc/nginx/html
sudo tee /etc/nginx/html/index.html <<< "Holberton School"
sudo tee /etc/nginx/html/404.html <<< "Ceci n'est pas une page"

# Configure Nginx with custom 404 page
sudo tee /etc/nginx/sites-available/default <<< "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}"

# Restart Nginx (without using systemctl)
sudo service nginx restart
