#!/usr/bin/env bash
# Bash script to install Nginx, modify content, and update configuration

# Update package information and install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Change index.html to read "Holberton School"
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

# Define lines for custom location and error page
lines="location /redirect_me {\n\trewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"
error_page_lines="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"

# Add custom lines to Nginx configuration
sudo sed -i "30i $lines$error_page_lines" /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
