#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Remove lines related to adding the HAProxy PPA
# apt-get install -y software-properties-common
# add-apt-repository -y ppa:vbernat/haproxy-1.8

apt-get update

# Install HAProxy from the official repository
apt-get install -y haproxy

# Create HAProxy configuration directory
sudo mkdir -p /etc/haproxy

load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b

backend load_b\n
\tbalance roundrobin
\tserver web-01 100.25.130.218:80 check
\tserver web-02 34.239.253.248:80 check
"

# Update the path for HAProxy configuration
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy
service haproxy restart

