#!/usr/bin/env bash
# Configure IP address resolution in /etc/hosts
LOCALHOST_IP="127.0.0.2"
FACEBOOK_IP="8.8.8.8"
sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i "s/^127.0.0.1/$LOCALHOST_IP/" /etc/hosts
echo "$FACEBOOK_IP	facebook.com" | sudo tee -a /etc/hosts
echo "Updated /etc/hosts file:"
cat /etc/hosts
