#!/usr/bin/env bash

# Change the port for nginx to 8080 and restart its service with the nginx user

# Modify nginx configuration
sed -i "s/80 default/8080 default/" /etc/nginx/sites-enabled/default

# Modify Apache ports configuration
sed -i "s/80/8080/" /etc/apache2/ports.conf

# Restart Apache service
sudo pkill apache2
sudo service apache2 restart
sudo service apache2 stop

# Grant read permissions to nginx.conf
sudo chmod +r /etc/nginx/nginx.conf

# Restart nginx service with the nginx user
sudo -u nginx service nginx restart

